/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PvButton: typeof import('primevue/button')['default']
    PvDrawer: typeof import('primevue/drawer')['default']
    PvInputText: typeof import('primevue/inputtext')['default']
    PvMenu: typeof import('primevue/menu')['default']
    PvMenubar: typeof import('primevue/menubar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
